### ISSUE TITLE
README.md and install script clarifications.

### ISSUE THREAD

**Issue by rct** [redhatdemocentral/cdk-install-demo#10]
There are a number of things that should be made clear in the README.md and the install script:
- it will only currently work with the version/path of the CDK it is currently hard coded for.  (beta4).
- CDK is currently beta,install instructions and this script may need to change for GA.
- The user is responsible for downloading all of the necessary bits, the script currently doesn't do any downloading

**Comment by eschabell** [comment]
This has been fixed since, sorry I did not see this issue sooner.
