### ISSUE TITLE
Ability to toggle vagrant providers

### ISSUE THREAD

**Issue by sabre1041** [redhatdemocentral/cdk-install-demo#4]
Especially for the Windows installation, it is possible for users to be able to utilize either the vmware fusion or vagrant CDK. Providing the ability to add a flag or instruct the user on the steps necessary to make these changes would be helpful

**Comment by eschabell** [comment]
Make it so! ;-)

**Comment by eschabell** [comment]
No longer needed with the fully automated installer.
