### ISSUE TITLE
We should Integrate ADB with cdk-install-demo

### ISSUE THREAD

**Issue by LalatenduMohanty** [redhatdemocentral/cdk-install-demo#5]
ADB i.e. Atomic Developer Bundle [1] is upstream of CDK and we should try to integrate this installer with it too. I am sure it will help the user community. 
I am one of the maintainer of ADB and available in #nulecule of #atomic (Freenode) if you want to discuss this.

[1] https://github.com/projectatomic/adb-atomic-developer-bundle

**Comment by eschabell** [comment]
Be in touch in a bit... (sorry am not getting notified when issue was raised).

**Comment by eschabell** [comment]
@LalatenduMohanty what are you suggesting to do? Integrating upstream projects is not the target of this project as we want to expose OpenShift product (not Origin) to the users on their local laptop. Make sense or are you suggesting something else?

**Comment by eschabell** [comment]
Closing as this is not part of this project, but more core to the CDK engineering.
