### ISSUE TITLE
Don't rmdir existing CDK directory tree.

### ISSUE THREAD

**Issue by rct** [redhatdemocentral/cdk-install-demo#7]
The install script (blindly) deletes an existing CDK directory if it already exists.

Aside from possibly causing the user to possibly loose data this can cause problems with Vagrant if you delete existing boxes that are in .vagrant without removing them first.   To work around this you'd need to delete ~/.vagrant.d and clean up existing VMs in Virtualbox.

**Comment by rct** [comment]
should have mentioned it is rmdir /s /q (install.bat) and rm -rf (install.sh)

Another suggestion when using environment variables as an arg to something like `rm -rf $CDK_HOME` it is usually best to wrap it as `${CDK_HOME?}` which will be an error in the shell if the env. is not set.    

The current usage is ok, but consider what happens if you had rm -rf $CDK_HOME/ and $CDK_HOME isn't set or you've got a typo.

**Comment by eschabell** [comment]
This is the desired behavior for the demo, it is intended to setup a fresh clean working installation every time. If you would like, modify that same removal line to first make a backup by moving the original installation.
